docker_build(
    ref='local/infumia/agones4j-example',
    context='./docker/',
    dockerfile='./docker/Dockerfile'
)

k8s_yaml(helm(
    './charts/',
    name='agones4j-example',
    namespace='example'
))

k8s_resource('example-fleet', resource_deps=['agones'])
