[versions]
grpc = "1.47.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.24" }
annotations = { module = "org.jetbrains:annotations", version = "23.0.0" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
annotationsapi = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }
terminable = { module = "tr.com.infumia:terminable", version = "0.1.1" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.8.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
protobuf = { id = "com.google.protobuf", version = "0.8.19" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
