[versions]
grpc = "1.59.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.30" }
annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
protobuf = { module = "com.google.protobuf:protobuf-java", version = "3.25.0" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
annotationsapi = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.22.0" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
