[versions]
grpc = "1.54.1"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.26" }
annotations = { module = "org.jetbrains:annotations", version = "24.0.1" }
protobuf = { module = "com.google.protobuf:protobuf-java", version = "3.22.3" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
annotationsapi = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }
terminable = { module = "tr.com.infumia:terminable", version = "0.1.3" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }
protobuf = { id = "com.google.protobuf", version = "0.9.3" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
