[versions]
grpc = "1.61.1"
protobuf = "3.25.2"

[libraries]
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
annotationsapi = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
