load('ext://helm_remote', 'helm_remote')
load('ext://namespace', 'namespace_create')

namespace_create('example')

helm_remote(
    'agones',
    namespace='agones-system',
    create_namespace=True,
    repo_url='https://agones.dev/chart/stable',
    values=['./values.yaml']
)

k8s_kind('Fleet', image_json_path='{.spec.template.spec.template.spec.containers.*.image}')

agones_resources = [
    'agones-controller',
    'agones-extensions',
    'agones-ping',
    'agones-allocator',
    'agones-delete-agones-resources'
]

for resource in agones_resources:
    k8s_resource(resource, labels=['agones'])

local_resource('agones', cmd='echo ready', resource_deps=agones_resources)
