---
name: "Release"
"on":
  release:
    types:
    - "released"
jobs:
  build:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "adopt"
        java-version: "11"
    - uses: "actions/cache@v4"
      with:
        path: "~/.gradle/caches"
        key: "${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}"
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: "actions/cache@v4"
      with:
        path: "~/.gradle/wrapper"
        key: "${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}"
        restore-keys: |
          ${{ runner.os }}-gradlew-
    - run: |
        [[ "${{ github.event.release.tag_name }}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
        chmod +x gradlew
        ./gradlew -Psign-required=true publish -Pversion="${{ github.event.release.tag_name }}" -PmavenCentralUsername="${{ secrets.MAVEN_CENTRAL_USERNAME }}" -PmavenCentralPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}" -PsigningInMemoryKey="${{ secrets.GPG_PRIVATE_KEY_ARMORED }}" -PsigningInMemoryKeyPassword="${{ secrets.GPG_PASSPHRASE }}"
